debug: false
comp_name: open-problems-multimodal
nb_name: localsrc001-multi-task
wandb: true
type: cite # multi
exp: exp001
_wandb_kernel: riow1983
apex: true
print_freq: 100
num_workers: 4
scheduler: cosine # ['linear', 'cosine']
batch_scheduler: true
num_cycles: 0.5
num_warmup_steps: 0
epochs: 5
encoder_lr: 2e-5
decoder_lr: 2e-5
min_lr: 1e-6
eps: 1e-6
betas:
- 0.9
- 0.999
batch_size: 12
fc_dropout: 0.2
weight_decay: 0.01
gradient_accumulation_steps: 1
max_grad_norm: 1000
seed: 42
n_fold: 3
trn_fold:
- 0
- 1
- 2
- 3
- 4
train: true
num_tasks: 144
num_features: 20856