debug: true
comp_name: open-problems-multimodal
nb_name: localsrc001-multi-task
kagglenb_name: kagglenb001
wandb: true
type: cite # multi
exp: exp001
_wandb_kernel: riow1983
apex: true
print_freq: 100
num_workers: 8
scheduler: cosine # ['linear', 'cosine']
batch_scheduler: true
num_cycles: 0.5
num_warmup_steps: 0
epochs: 5
encoder_lr: 2.0e-5
decoder_lr: 2.0e-5
min_lr: 1.0e-6
eps: 1.0e-6
betas:
- 0.9
- 0.999
batch_size: 1
fc_dropout: 0.2
weight_decay: 0.01
gradient_accumulation_steps: 1
max_grad_norm: 1000
seed: 42
n_fold: 3
trn_fold:
- 0
- 1
- 2
train: true
num_tasks: 140
num_features: 22050